#!/bin/bash

## Fill in name of program here.
PROG="tomcat"
PROG_PATH="/root/apache-tomcat-7.0.82/bin" ## Not need, but sometimes helpful (if $PROG resides in /opt for example).
PROG_ARGS=""
PID_PATH="/var/run"

#set java environment
  JAVA_HOME=/root/jdk1.8.0_151
  JRE_HOME=/root/jdk1.8.0_151/jre
  PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin
  CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:$JRE_HOME/lib
  JBOSS_HOME=/root/jboss-as-web-7.0.0.Final
  export JAVA_HOME JRE_HOME CLASSPATH JBOSS_HOME

start() {
        echo "tomcat starting"
        echo "$PID_PATH/$PROG.pid"
    if [ -e "$PID_PATH/$PROG.pid" ]; then
        ## Program is running, exit with error.
        echo "Error! $PROG is currently running!" 1>&2
        exit 1
    else
        ## Change from /dev/null to something like /var/log/$PROG if you want to save output.
        bash /etc/profile
        # $PROG_PATH/startup.sh $PROG_ARGS 2>&1 >/var/log/$PROG &
        # echo "where am I"
        # $pid=`ps ax | grep -i 'tomcat' | sed 's/^\([0-9]\{1,\}\).*/\1/g' | head -n 1`
        echo "this is tomcat"
        #source /etc/profile
        $PROG_PATH/startup.sh
        echo "$PROG started..."
        echo $pid > "$PID_PATH/$PROG.pid"
        echo "..............................."
    fi
}

stop() {
    echo "begin stop"
    if [ -e "$PID_PATH/$PROG.pid" ]; then
        ## Program is running, so stop it
        # pid=`ps ax | grep -i 'tomcat' | sed 's/^\([0-9]\{1,\}\).*/\1/g' | head -n 1`
        # kill $pid

        rm -f  "$PID_PATH/$PROG.pid"
        $PROG_PATH/shutdown.sh
        echo "$PROG stopped"
    else
        ## Program is not running, exit with error.
        echo "Error! $PROG not started!" 1>&2
        exit 1
    fi
}

## Check to see if we are running as root first.
## Found at http://www.cyberciti.biz/tips/shell-root-user-check-script.html
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

case "$1" in
    start)
        start
        exit 0
    ;;
    stop)
        stop
        exit 0
    ;;
    reload|restart|force-reload)
        stop
        start
        exit 0
    ;;
    **)
        echo "Usage: $0 {start|stop|reload}" 1>&2
        exit 1
    ;;
esac
